name: smartrecorder
description: An smart recording application

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  page_transition: ^1.1.5
  back_button_interceptor: ^4.2.3
  gradient_app_bar: ^0.1.3
  flutter_sound: ^4.0.1+1
  path_provider: ^1.6.7
  share_extend: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
